apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: db-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-postgres
  template:
    metadata:
      labels:
        app: db-postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: Always
          env:
          - name: POSTGRES_DB
            value: fastapi 
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fastapi-secrets
                key: db_postgres_password
          ports:
          - containerPort: 5432
            name: db-container
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    name: postgres
  selector:
    app: db-postgres
  type: LoadBalancer
